# Generated by Django 4.2.2 on 2023-06-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner Image', 'verbose_name_plural': 'Banner Images'},
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default=None, max_length=300)),
                ('course_name', models.CharField(max_length=300)),
                ('duration', models.CharField(default=None, max_length=300)),
                ('fees', models.CharField(default=None, max_length=300)),
                ('details', models.CharField(default=None, max_length=300)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category')),
            ],
            options={
                'verbose_name': 'University Course',
                'verbose_name_plural': 'University Courses',
            },
        ),
    ]
