# Generated by Django 4.2.2 on 2023-06-28 10:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_banner_options_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
