# Generated by Django 4.2.2 on 2023-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='detail',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
