# Generated by Django 4.2.2 on 2023-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_banner_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
