# Generated by Django 4.2.2 on 2023-06-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_courseoffering_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='certificate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='fees',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='language',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
