# Generated by Django 4.2.2 on 2023-06-30 19:39

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_courseoffering_certificate_courseoffering_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(choices=[('One Week', 'One Week'), ('Two Weeks', 'Two Weeks'), ('Three Weeks', 'Three Weeks'), ('Four Weeks', 'Four Weeks')], default=None, max_length=300),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_country', django_countries.fields.CountryField(max_length=2)),
                ('company_city', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('declaration', models.BooleanField()),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.courseoffering')),
            ],
        ),
    ]
